@UserManagementAPI_HostAddress = http://localhost:5298
@SecretKey = your-secret-api-key-ABCDE
### OpenAPI Specification

GET {{UserManagementAPI_HostAddress}}/openapi/v1.json
Authorization: Bearer {{SecretKey}}
Accept: application/json

### GET

GET {{UserManagementAPI_HostAddress}}/api/Users
Authorization: Bearer {{SecretKey}}
Accept: application/json

### POST

POST {{UserManagementAPI_HostAddress}}/api/Users
Authorization: Bearer {{SecretKey}}
Content-Type: application/json

{
    "name": "test - Name",
    "email": "test@email.ca"
}

### PUT

PUT {{UserManagementAPI_HostAddress}}/api/Users/1
Authorization: Bearer {{SecretKey}}
Content-Type: application/json

{
    "name": "test - Name 1",
    "email": "test1@email.ca"
}

### DELETE

DELETE {{UserManagementAPI_HostAddress}}/api/Users/1
Authorization: Bearer {{SecretKey}}
Content-Type: application/json

### MiddleWare to get route counts

GET {{UserManagementAPI_HostAddress}}/api/Users/route-counts
Authorization: Bearer {{SecretKey}}
Content-Type: application/json

### MiddleWare to Error Handling

GET {{UserManagementAPI_HostAddress}}/api/Users/eee
Authorization: Bearer {{SecretKey}}
Content-Type: application/json