@UserManagementAPI_HostAddress = http://localhost:5298

### OpenAPI Specification

GET {{UserManagementAPI_HostAddress}}/openapi/v1.json
Accept: application/json

### GET

GET {{UserManagementAPI_HostAddress}}/api/Users
Accept: application/json

### POST

POST {{UserManagementAPI_HostAddress}}/api/Users
Content-Type: application/json

{
    "name": "test - Name",
    "email": "test@email.ca"
}

### PUT

PUT {{UserManagementAPI_HostAddress}}/api/Users/1
Content-Type: application/json

{
    "name": "test - Name 1",
    "email": "test1@email.ca"
}

### DELETE

DELETE {{UserManagementAPI_HostAddress}}/api/Users/1
Content-Type: application/json

### MiddleWare to get route counts

GET {{UserManagementAPI_HostAddress}}/api/Users/route-counts
Content-Type: application/json